Home.files turn-in
BlackJackMC/dummyfrontend pull request #3
Opened 2024-05-27 02:48 UTC by JerryTruong2510

2024-05-27 12:06 UTC, BlackJackMC requested changes
**Overall**:
- Nhìn chung là t không biết m thay đổi thêm bớt cái gì
- File structure của m không khớp main
- Icon là font chứ không phải hình

**Html**:
- File structure không khớp, không được thay đổi ID của html

**CSS**:
- T chịu, hoặc là m làm lại hết, hoặc là label ra thay đổi cái gì

**Material**:
- M nên xem lại phần head để biết tụi t đang làm gì

2024-05-28 02:08 UTC, JerryTruong2510 reviewed
T thêm comment ở những phần nào t chỉnh rồi á

2024-05-28 02:08 UTC, JerryTruong2510 commented on home.html
>              <div class="row">
section-3 phần .row, bỏ column-1 và column-2 => row thành container cho 8 products

2024-05-28 02:08 UTC, JerryTruong2510 commented on home.html
> +                    <div class="hidden-info">
Hidden-info là phần khi hover sẽ hiện lên

2024-05-28 02:08 UTC, JerryTruong2510 commented on home.html
> +                    <div class="hidden-info">
Mỗi product đều có 1 clone của hidden-info

2024-05-28 02:08 UTC, JerryTruong2510 commented on css/home.css
> +  margin-top: 15vh;
Cái margin thì do t thấy nó bị thằng header che một phần nên t margin-top = height thằng header để tránh bị che thôi

2024-05-28 02:08 UTC, JerryTruong2510 commented on css/home.css
>  #hero-inform-box {
Modifications ở đây là để cho nó giống giống des bên eCommerce

2024-05-28 02:08 UTC, JerryTruong2510 commented on css/home.css
> +
min() với max() từ #hero-box-heading-1 đến #hero-buy-now-button là dùng cho responsive design, nếu width có thay đổi thì nó cũng đổi theo cho đỡ rối

2024-05-28 02:08 UTC, JerryTruong2510 commented on css/universal.css
> +  height: 15vh;
height ở đây là để t margin-top cho thằng section-1

2024-05-28 02:08 UTC, JerryTruong2510 commented on css/universal.css
> +  z-index: 100;
Chạy xuống thì thấy header bị mấy cái button che nên set vậy cho chắc

2024-05-28 02:10 UTC, JerryTruong2510 commented on home.html
>              <div class="row">
Để lúc flex-wrap thì nó dồn đều xuống, lúc đầu thì nó bị ratio hàng 3:1 elements (hàng trên 3 elements hàng dưới 1 element đối với mỗi column)

2024-05-28 02:17 UTC, BlackJackMC requested changes
Check lại branch của m so với HEAD của main

2024-05-28 11:40 UTC, closed without merging